### ISSUE TITLE
new Mapland icon

### ISSUE THREAD

**Issue by barrybecker4** [LoganCSC/MapLand#19]
The current one comes form the map api demos and should be replaced with one that you created.

**Comment by brianjamesbecker** [comment]
ok i did this one

**Comment by barrybecker4** [comment]
If it is done, please push to your branch and do a pull request. 
I will then review and merge it to master.

**Comment by barrybecker4** [comment]
If its done, where is the pull request? It's not done until the pull request as been reviewed, merged to master, and tested.

**Comment by barrybecker4** [comment]
Brian, I will close this now because you added the new icon and it is integrated on master.
Thank you!
